### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0

### ISSUE THREAD

**Issue by HugoHann** [justchenhao/BIT_CD#25]
When I run scripts/eval.sh, there is an error.
```
Traceback (most recent call last):
  File "eval_cd.py", line 59, in <module>
    main()
  File "eval_cd.py", line 55, in main
    model.eval_models(checkpoint_name=args.checkpoint_name)
  File "/mnt/data/home/hanx/BIT_CD/models/evaluator.py", line 171, in eval_models
    self._collect_running_batch_states()
  File "/mnt/data/home/hanx/BIT_CD/models/evaluator.py", line 105, in _collect_running_batch_states
    running_acc = self._update_metric()
  File "/mnt/data/home/hanx/BIT_CD/models/evaluator.py", line 100, in _update_metric
    current_score = self.running_metric.update_cm(pr=G_pred.cpu().numpy(), gt=target.cpu().numpy())
  File "/mnt/data/home/hanx/BIT_CD/misc/metric_tool.py", line 56, in update_cm
    val = get_confuse_matrix(num_classes=self.n_class, label_gts=gt, label_preds=pr)
  File "/mnt/data/home/hanx/BIT_CD/misc/metric_tool.py", line 157, in get_confuse_matrix
    confusion_matrix += __fast_hist(lt.flatten(), lp.flatten())
  File "/mnt/data/home/hanx/BIT_CD/misc/metric_tool.py", line 152, in __fast_hist
    hist = np.bincount(num_classes * label_gt[mask].astype(int) + label_pred[mask],
IndexError: boolean index did not match indexed array along dimension 0; dimension is 65536 but corresponding boolean dimension is 196608
```
Could you please help me solve this?

**Comment by HugoHann** [comment]
> 

I followed the paper, cut images into small patches of size 256 × 256 with no overlap and solved it.
